language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
sudo: false
env:
  - DJANGO_VERSION=1.8.10 DJANGO_DB_ENGINE=sqlite
  - DJANGO_VERSION=1.8.10 DJANGO_DB_ENGINE=postgres DJANGO_DB_NAME=testdb DJANGO_DB_USER=postgres
  - DJANGO_VERSION=1.8.10 DJANGO_DB_ENGINE=mysql DJANGO_DB_NAME=testdb DJANGO_DB_USER=travis
  - DJANGO_VERSION=1.9.3 DJANGO_DB_ENGINE=sqlite
  - DJANGO_VERSION=1.9.3 DJANGO_DB_ENGINE=postgres DJANGO_DB_NAME=testdb DJANGO_DB_USER=postgres
  - DJANGO_VERSION=1.9.3 DJANGO_DB_ENGINE=mysql DJANGO_DB_NAME=testdb DJANGO_DB_USER=travis
install:
  - pip install "Django==$DJANGO_VERSION" MySQL-python psycopg2
  - "pip install flake8 pylint pylint-django django-nose"
  - "pip install -e ."
before_script:
  - "mysql -e 'create database testdb;'"
  - "psql -c 'create database testdb;' -U postgres"
script:
  - "python setup.py test"
  - "./lint.sh"
matrix:
  exclude:
    - python: 3.2
      env: DJANGO_VERSION=1.9.3
    - python: 3.3
      env: DJANGO_VERSION=1.9.3
    - python: 3.5
      env: DJANGO_VERSION=1.8.10
